import { Product1, Product2, Product3, Product4 } from "../assets";

export const AdvertMessage = [
  {
    id: 1,
    text: "We got you covered for good selection for christmas",
    image: "",
    to: "",
    backGroundImg: "",
  },
  {
    id: 2,
    text: "Merry Christmas and Happy new year",
    image: "",
    to: "/Mall",
    backGroundImg: "",
  },
  {
    id: 3,
    text: "We will never call you for yuur card etails",
    image: "",
    to: "/Mall",
    backGroundImg: "",
  },
  {
    id: 4,
    text: "Shop on budget and tust us with your enjoyment",
    image: "",
    to: "/Mall",
    backGroundImg: "",
  },
  {
    id: 5,
    text: "By one and get 20 free",
    image: "",
    to: "/school",
    backGroundImg: "",
  },
  {
    id: 6,
    text: "Protect your card details",
    image: "",
    to: "",
    backGroundImg: "",
  },
];

export const sliderCard = [
  {
    id: 7,
    style: "carousel1",
    productImg: Product1,
    collectionTitle:
      "FoodsbyMomi: Premium Quality Foods for Households and Businesses Worldwide",
    collectionDecription:
      "We provide hygienically processed and packaged, premium FDA-approved foods for the global export market, fully compliant with all regulatory standards. Our offerings include cost-effective B2B solutions such as contract manufacturing and white labeling, tailored for African and Caribbean stores worldwide, as well as small-scale food ventures. FoodsbyMomi products are perfect for both household consumers and businesses.",

    // productCard
    title: "POUNDO YARM FLOUR 'IYAN'",
    categories: [
      "Food",
      "keg",
      "Grains and Flours",
      "Health and wellness",
      "Popular product",
      "Recently added",
      "Ready made food",
      "Packaged food",
    ],
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
  },
  {
    id: 8,
    style: "carousel1",
    productImg: Product2,
    collectionTitle:
      "FoodsbyMomi: Premium Quality Foods for Households and Businesses Worldwide",
    collectionDecription:
      "We provide hygienically processed and packaged, premium FDA-approved foods for the global export market, fully compliant with all regulatory standards. Our offerings include cost-effective B2B solutions such as contract manufacturing and white labeling, tailored for African and Caribbean stores worldwide, as well as small-scale food ventures. FoodsbyMomi products are perfect for both household consumers and businesses.",

    // productCard
    title: "EGGPLANT SWALLOW",
    categories: [
      "Food",
      "keg",
      "Grains and Flours",
      "Health and wellness",
      "Popular product",
      "Recently added",
      "Ready made food",
      "Packaged food",
    ],
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
  },
  {
    id: 9,
    style: "carousel1",
    productImg: Product3,
    collectionTitle:
      "FoodsbyMomi: Premium Quality Foods for Households and Businesses Worldwide",
    collectionDecription:
      "We provide hygienically processed and packaged, premium FDA-approved foods for the global export market, fully compliant with all regulatory standards. Our offerings include cost-effective B2B solutions such as contract manufacturing and white labeling, tailored for African and Caribbean stores worldwide, as well as small-scale food ventures. FoodsbyMomi products are perfect for both household consumers and businesses.",

    // productCard
    title: "CABBAGE SWALLOW",
    categories: [
      "Food",
      "keg",
      "Health and wellness",
      "Popular product",
      "Recently added",
      "Ready made food",
      "Packaged food",
    ],
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
  },
  {
    id: 10,
    style: "carousel1",
    productImg: Product4,
    collectionTitle: "Savor the Flavor: Unforgettable Culinary Creations",
    collectionDecription:
      "We provide hygienically processed and packaged, premium FDA-approved foods for the global export market, fully compliant with all regulatory standards. Our offerings include cost-effective B2B solutions such as contract manufacturing and white labeling, tailored for African and Caribbean stores worldwide, as well as small-scale food ventures. FoodsbyMomi products are perfect for both household consumers and businesses.",

    // productCard
    title: "POUNDO YARM FLOUR",
    categories: [
      "Food",
      "keg",
      "Health and wellness",
      "Popular product",
      "Recently added",
      "Ready made food",
      "Packaged food",
    ],
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
  },
  {
    id: 11,
    style: "carousel1",
    productImg: Product4,
    collectionTitle: "Savor the Flavor: Unforgettable Culinary Creations",
    collectionDecription:
      "We provide hygienically processed and packaged, premium FDA-approved foods for the global export market, fully compliant with all regulatory standards. Our offerings include cost-effective B2B solutions such as contract manufacturing and white labeling, tailored for African and Caribbean stores worldwide, as well as small-scale food ventures. FoodsbyMomi products are perfect for both household consumers and businesses.",

    // productCard
    title: "POUNDO YARM FLOUR",
    categories: [
      "Food",
      "keg",
      "Health and wellness",
      "Popular product",
      "Recently added",
      "Ready made food",
      "Packaged food",
    ],
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
  },
  {
    id: 12,
    style: "carousel1",
    productImg: Product4,
    collectionTitle: "Savor the Flavor: Unforgettable Culinary Creations",
    collectionDecription:
      "We provide hygienically processed and packaged, premium FDA-approved foods for the global export market, fully compliant with all regulatory standards. Our offerings include cost-effective B2B solutions such as contract manufacturing and white labeling, tailored for African and Caribbean stores worldwide, as well as small-scale food ventures. FoodsbyMomi products are perfect for both household consumers and businesses.",

    // productCard
    title: "POUNDO YARM FLOUR",
    categories: [
      "Food",
      "keg",
      "Health and wellness",
      "Popular product",
      "Recently added",
      "Ready made food",
      "Packaged food",
    ],
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
  },
  {
    id: 13,
    style: "carousel1",
    productImg: Product4,
    collectionTitle: "Savor the Flavor: Unforgettable Culinary Creations",
    collectionDecription:
      "From savory starters to mouthwatering mains, our menu is a celebration of flavors from around the world. Try our signature [dish name], a symphony of perfectly balanced ingredients that will transport you to food paradise.",

    // productCard
    title: "POUNDO YARM FLOUR",
    categories: [
      "Food",
      "keg",
      "Health and wellness",
      "Popular product",
      "Recently added",
      "Ready made food",
      "Packaged food",
    ],
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
  },
  {
    id: 14,
    style: "carousel1",
    productImg: Product4,
    collectionTitle: "Savor the Flavor: Unforgettable Culinary Creations",
    collectionDecription:
      "From savory starters to mouthwatering mains, our menu is a celebration of flavors from around the world. Try our signature [dish name], a symphony of perfectly balanced ingredients that will transport you to food paradise.",

    // productCard
    title: "POUNDO YARM FLOUR",
    categories: [
      "Food",
      "keg",
      "Health and wellness",
      "Popular product",
      "Recently added",
      "Ready made food",
      "Packaged food",
    ],
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
  },
];
